
FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000

WORKDIR /app/FlaskCeroNuestro/app.py

ENTRYPOINT [ "python3", "/app/FlaskCeroNuestro/app.py"]